name: Deploy a Datasette branch as a preview

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        type: string

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install datasette-publish-vercel
    - name: Deploy the preview
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        export BRANCH="${{ github.event.inputs.branch }}"
        wget https://latest.datasette.io/fixtures.db
        datasette publish vercel fixtures.db \
          --branch $BRANCH \
          --project "datasette-preview-$BRANCH" \
          --token $VERCEL_TOKEN \
          --alias "preview-$BRANCH.datasette.io"
